name = "MokTech Industries - Template"
prefix = "mti_template"
author = "MokTech Industries"
mainprefix = "z"

[version]
git_hash = 0

[asc]
enabled = true
exclude = [
    "/initsettings.sqf",
    "/initkeybinds.sqf",
    "/xeh_prep.sqf",
    "/XEH_preInit.sqf",
]

[hemtt.release]
archive = true
